FROM apache/spark-py:v3.4.0
USER root

WORKDIR /app

RUN apt-get update \ 
 && apt-get install -y --no-install-recommends libjemalloc2 \ 
 && rm -rf /var/lib/apt/lists/* \
 && pip install --no-cache-dir psycopg2-binary

COPY *.py .

COPY ./jars/*.jar /opt/spark/jars/

RUN chown -R 185:185 /app /opt/spark/jars

USER 185